### ISSUE TITLE
Does not show quests after most recient patch 23.6

### ISSUE THREAD

**Issue by chWolfgang** [ardittristan/HearthstoneQuestOverlay#10]
Greetings!
I really hope you are able to fix this. This is a fantastic add-in.

After 23.6 the quests no longer show. The screen overlay is there and there are no errors reported by HDT. I would be glad to do what I can to help/test but I am not that good of a coder. 

TYVM

**Comment by ardittristan** [comment]
weird, it still seems to work for me, what quests do you have active?

**Comment by s3ofor3v3r** [comment]
Same for me no errors reported but since 23.6 i see the quest overlay in the corner but when I put my mouse cursor over it nothing happens and the quest list does not appear. 
: /

**Comment by chWolfgang** [comment]
It was for the weekly quests and the dailies quests since the patch. Today and yesterday I had the play 3 games from one of three classes quests and it didn't work. Still no error.

**Comment by chWolfgang** [comment]
I have tried turning off other add-ons and deleting and reinstalling and still has the same issue. Do you have any idea of what else to try? Maybe a layering issue from something? Any help would be appreciated. Thank you.

**Comment by gmanc2** [comment]
@ardittristan Same issue here. Are you using the exact same build as us?

**Comment by ardittristan** [comment]
sorry, was on holiday.

weird, it still works for me and I'm on the same version, what does your plugin directory look like? is the plugin directly in the Plugins folder or a subdirectory?

**Comment by ardittristan** [comment]
I'll check what happens when I regenerate the image files, maybe something changed there

**Comment by ardittristan** [comment]
> I'll check what happens when I regenerate the image files, maybe something changed there

still works, hm

**Comment by JL276** [comment]
Also having this issue on HDT 1.18.8. The mercenaries quest overlay works though oddly enough (granted that isn't a plugin but they serve similar functionalities)

**Comment by chWolfgang** [comment]
I noticed the new release. I have it ready to go, but I don't have any quests. I will let you know tomorrow. Thank you for working on it.

**Comment by chWolfgang** [comment]
Actually, I just got an "All Quests Completed - check back in 7 hours" pop up. Great!!!

**Comment by chWolfgang** [comment]
It is showing this morning's quest just fine. Seems to be back working great. TYVM!!
