### ISSUE TITLE
I'm a dumbass and need help with install!

### ISSUE THREAD

**Issue by CryPB** [ardittristan/HearthstoneQuestOverlay#12]
How do i install this overlay? I have tried to figure this out for over an hour now and honestly i just can't figure it out. Could someone walk me through it?

**Comment by arm210402** [comment]
U can watch youtube tutorial https://www.youtube.com/watch?v=awzqCNNpgFg

**Comment by CryPB** [comment]
Could you link a reliable one?

**Comment by CryPB** [comment]
I know how to install plugins for hs deck tracker but i can't find a .dll file for this.

**Comment by ardittristan** [comment]
latest release is at https://github.com/ardittristan/HearthstoneQuestOverlay/releases

and then you drag the content of the zip into the plugins folder
![image](https://user-images.githubusercontent.com/42787508/182691199-e7e80b53-7209-491c-a1ed-a8d86b1a4c7f.png)

**Comment by CryPB** [comment]
Ah yes there we go. I just downloaded the wrong one. Thanks a lot man!
