### ISSUE TITLE
Same issue after this patch

### ISSUE THREAD

**Issue by chWolfgang** [ardittristan/HearthstoneQuestOverlay#13]
Greetings,
Unfortunately, I seem to have the same issue as last time after this patch. The overlay is on the screen, but when you try to use it you get nothing. 

I hope this a quick fix, I love this add on.

Thanks for your time!!

**Comment by s3ofor3v3r** [comment]
Same here ... :'(

**Comment by ardittristan** [comment]
For whatever reason HearthMirror does not like the new reward system layout, so it'll need some more time to be fixed.

**Comment by ardittristan** [comment]
I currently don't have enough time to fix it sadly, tried for 3 hours. A lot of internal structure around quests changed.

**Comment by sebastientromp** [comment]
In case that helps, this is the commit that I did for Firestone: https://github.com/Zero-to-Heroes/unity-spy-.net4.5/commit/0bbff22ab5799b97b178e054f0d8ff3d3fd51a56

It should give you more or less the info on how to handle the new structure in memory.

**Comment by ardittristan** [comment]
> In case that helps, this is the commit that I did for Firestone: [Zero-to-Heroes/unity-spy-.net4.5@0bbff22](https://github.com/Zero-to-Heroes/unity-spy-.net4.5/commit/0bbff22ab5799b97b178e054f0d8ff3d3fd51a56)
> 
> It should give you more or less the info on how to handle the new structure in memory.

The issue I'm having is that hearthmirror breaks on `m_rewardTrackEntries` and the `entries` property returns nonsensical data (seems like some error in reading). I don't know hearthmirror well enough to fix this. And since they already have some reward track code in hearthmirror which isn't updated to the new version yet I hope they'll fix it and then I can use it as well.

**Comment by ardittristan** [comment]
I won't have time to code until Wednesday, so I'll look at it again on Wednesday!

**Comment by sebastientromp** [comment]
Ah got it, in that case there's nothing I can do to help, but they should indeed fix this pretty quickly. Good luck!

**Comment by sebastientromp** [comment]
(m_rewardTrackEntries is a VAR type if I recall correctly, maybe they haven't implemented it yet)

**Comment by ardittristan** [comment]
I have it working now by manually parsing the object instead of letting the autoparser do it. Though the quest image assetbundle also changed, so I'll have to fix that as well.

**Comment by ardittristan** [comment]
Still haven't found the assetbundle that contains the quest icons. I can continue fixing on Saturday.

**Comment by ardittristan** [comment]
Nvm, had 2 hours free today. Semi fix is pushed, but still needs some work (though technically it fully works again, just a bit ugly since it also includes battlegrounds quests)

**Comment by chWolfgang** [comment]
It does seem to be working again!! TYVM

**Comment by ardittristan** [comment]
Fully closed with 1.5.0
