### ISSUE TITLE
Exception when HDT Config is not saved in AppData + Overlay not updating when a match has finished

### ISSUE THREAD

**Issue by keima1987** [ardittristan/HearthstoneQuestOverlay#14]
Hello, 

I've found 2 issues with the actual version (1.5.7) of the plugin:
 
1. When the Configuration file of HDT is **not** saved in AppData (Options > Settings > Save config in AppData (Advanced options must be enabled to see this option), I'll get the following Exception from HDT:
```
System.UriFormatException: Ungültiger URI: Das URI-Format konnte nicht bestimmt werden.
   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei System.Uri..ctor(String uriString, UriKind uriKind)
   bei QuestOverlayPlugin.Util.Icon.GetImageUri(String fileName)
   bei QuestOverlayPlugin.Util.Icon.get_NormalIcon()
   bei QuestOverlayPlugin.Util.Icon..ctor(String name, String assetBundle)
   bei QuestOverlayPlugin.Overlay.QuestViewModel..ctor(Quest quest)
   bei QuestOverlayPlugin.Overlay.QuestListViewModel.<Update>b__20_0(Quest quest)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Buffer``1..ctor(IEnumerable`1 source)
   bei System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei QuestOverlayPlugin.Overlay.QuestListViewModel.Update(Boolean force)
   bei QuestOverlayPlugin.Plugin.ShowQuests()
   bei QuestOverlayPlugin.Overlay.QuestListButton.<OnMouseEnter>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Image:
![image](https://github.com/ardittristan/HearthstoneQuestOverlay/assets/31212655/317813f4-1147-4b8c-8696-8c65ad1e9e1a)

2. I also have another issue when a match is over, the overlay doesn't update.

Image:
![image](https://github.com/ardittristan/HearthstoneQuestOverlay/assets/31212655/fb02fe5e-acb1-44ff-b374-9d13c211cdae)

Versions:
Heathstone: 26.4.3.178555.175913
Heathstone Deck Tracker: 1.20.9 - 2023-06-15
Heathstone Quest Overlay Plugin: 1.5.7

I hope this helps.

Greetings from Luxembourg,
Keima1987 😎

**Comment by ardittristan** [comment]
Figured out the issue with the error. When asking HearthstoneDeckTracker for the config directory, it returns nothing instead of the non-appdata directory, making the URI break. With the next update I'm making the URI accept relative paths as well.

**Comment by keima1987** [comment]
Alright. Thanks :)
