### ISSUE TITLE
Overlay won't show quests when hovered over?

### ISSUE THREAD

**Issue by otarauhas** [ardittristan/HearthstoneQuestOverlay#15]
Battlegrounds overlay works just fine but the normal one doesn't.

**Comment by ardittristan** [comment]
![image](https://github.com/ardittristan/HearthstoneQuestOverlay/assets/42787508/6c9dc9ea-0cd0-4c56-9bb5-f11905332f68)
weird, it seems to work fine for me (except for the images, looking into that)

do you remember which quests you had?

**Comment by ardittristan** [comment]
nvm, found the issue. Every update Hearthstone now changes the assetbundle names. So I'll have to find a new way to find the correct assetbundle
