### ISSUE TITLE
I got This Error :(

### ISSUE THREAD

**Issue by SimonDeLaus89** [ardittristan/HearthstoneQuestOverlay#4]
(Sorry, that the Exception is on German :/ )

Make sure you are using the latest version of the Plugin and HDT.

System.Windows.Markup.XamlParseException: Durch den Aufruf des Konstruktors für Typ "QuestOverlayPlugin.Stub.HearthstoneTextBlockStub", der den angegebenen Bindungseinschränkungen entspricht, wurde eine Ausnahme ausgelöst. ---> System.Exception: Die Komponente "QuestOverlayPlugin.Stub.HearthstoneTextBlockStub" verfügt nicht über eine Ressource, die vom URI "/HearthstoneDeckTracker;V1.17.12.5770;component/controls/hearthstonetextblock.xaml" identifiziert wird.
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei Hearthstone_Deck_Tracker.HearthstoneTextBlock.InitializeComponent() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Controls\HearthstoneTextBlock.xaml:Zeile 1.
   bei QuestOverlayPlugin.Stub.HearthstoneTextBlockStub..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   bei System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   bei System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   bei System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   bei System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   bei System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   bei System.Windows.FrameworkElement.ApplyTemplate()
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.StackPanel.StackMeasureHelper(IStackMeasure measureElement, IStackMeasureScrollData scrollData, Size constraint)
   bei System.Windows.Controls.StackPanel.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   bei System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.Border.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.Control.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.StackPanel.StackMeasureHelper(IStackMeasure measureElement, IStackMeasureScrollData scrollData, Size constraint)
   bei System.Windows.Controls.StackPanel.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   bei System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.Border.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.Control.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.Controls.Canvas.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.ContextLayoutManager.UpdateLayout()
   bei System.Windows.UIElement.UpdateLayout()
   bei Hearthstone_Deck_Tracker.Windows.OverlayElementBehavior.Show() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Utility\Overlay\OverlayElementBehavior.cs:Zeile 125.
   bei QuestOverlayPlugin.Plugin.ShowQuests()
   bei QuestOverlayPlugin.Overlay.QuestListButton.<OnMouseEnter>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chWolfgang** [comment]
I can confirm I got the same or very similar error with the new version. The older one seems to work ok. When I tried to switch back to the older version I got the same error. I hope this is an easy fix. I think this is a great add-on.

Thanks for your efforts!
