### ISSUE TITLE
A new problem when using

### ISSUE THREAD

**Issue by TheMrKochan** [ardittristan/HearthstoneQuestOverlay#9]
It appeared after unknown actions, it does not interfere with work, but an error hangs in HDT. Sorry that part of the text is in Russian(
![Скриншот 22-05-2022 174218](https://user-images.githubusercontent.com/75619070/169701034-2951e95e-a96e-41ef-8b66-183d07fe0f85.jpg)

**Comment by ardittristan** [comment]
Which quests did you have when the error occurred?

**Comment by ComeSeeMePlay** [comment]
![image](https://user-images.githubusercontent.com/56169823/170436584-0d86a98b-fa1c-41b4-85f4-ce8c7af05492.png)
Got the same issue :)

**Comment by ComeSeeMePlay** [comment]
Hmm i can't check the quests again since I completed them, but I think you mean if the initial_prog_global-0 folder has content, and I saw it only had 4 files before I deleted it and restarted HS. After that it filled up as normal :)

**Comment by TheMrKochan** [comment]
> Which quests did you have when the error occurred?

![image](https://user-images.githubusercontent.com/75619070/170841446-0d5467a4-7d7b-4f96-8d92-cfbf06d1d2da.png)
![image](https://user-images.githubusercontent.com/75619070/170841451-a268eb2a-f702-4c77-b2db-8aa9630f03b0.png)
